import type { ImgHTMLAttributes } from "react";
import Link from "next/link";

const A = "/assets/";
type SiteImageProps = ImgHTMLAttributes<HTMLImageElement> & { priority?: boolean };
const Image = ({ priority: _priority, ...props }: SiteImageProps) => <img {...props} />;

export function Header({ active }: { active: "home" | "schedule" | "coach" | "about" }) {
  return <header className="header"><Link href="/" className="logo" aria-label="3Motions home"><Image src={`${A}3motions-logo.png`} alt="3Motions" width={142} height={45} priority /></Link><nav><Link className={active === "home" ? "active" : ""} href="/">Home</Link><Link className={active === "schedule" ? "active" : ""} href="/schedule">Schedule</Link><Link className={active === "coach" ? "active" : ""} href="/our-coach">Our Coach</Link><Link className={active === "about" ? "active" : ""} href="/about-us">About Us</Link><a className="member" href="mailto:hello@3motions.id">Member Area</a></nav></header>;
}

function Footer() { return <footer><Image src={`${A}3motions-logo.png`} alt="3Motions" width={130} height={41}/><p>©2026 PT Teman Naik Kelas, Indonesia, Jakarta</p></footer>; }
const Button = ({children="Daftar Sekarang"}:{children?:string}) => <a className="button" href="mailto:hello@3motions.id?subject=Pilates%20Registration">{children}</a>;

const testimonials = [
  ["People-1.png", "Lonny", "Jadi sangat paham dengan tekniknya. Privasinya terjaga banget. Coach-nya super sabar."],
  ["people-2.png", "Amanda R.", "Badan kerasa jauh lebih fungsional setelah rutin latihan di sini. Alatnya masih baru dan bersih."],
  ["people-3.png", "Ibu Nia", "Bener-bener sanctuary buat ibu rumah tangga kayak aku. Abis latihan bisa langsung relaksasi."],
  ["people-4.png", "Sarah", "Sesi yang personal dan terarah. Aku jadi lebih percaya diri dengan tubuhku sendiri."],
];

export function HomePage() { return <><Header active="home" /><main>
  <section className="hero home-hero"><div className="hero-content"><p className="eyebrow">Pilates studio Bogor</p><h1>Elevate Your Movement,<br/>Transform Your Soul</h1><p>Eksklusif di jantung kota Bogor. Rasakan pengalaman pilates privat yang menggabungkan presisi gerakan dengan ketenangan batin yang hakiki.</p><Button>Daftar Sesi Trial</Button></div></section>
  <section className="reservation"><h2>Book Your Reservation!</h2><div className="reservation-grid"><div><p className="eyebrow red">The Serenity Experience</p><h3>Mat Pilates Bogor</h3><p>Kami menyapa setiap member sebagai “Angels”. Di sini, transformasi bukan sekadar fisik, melainkan harmoni antara kontrol tubuh dan fokus pikiran.</p><p><b>Sabtu, 29 August 2026 (07.00 - 19.00 WIB)</b><br/>W-Clugra Racha Laras Bogor, Kec. Bogor Utara, Kota Bogor.</p><Button /></div><Image className="rounded-image" src={`${A}AdobeStock_927779186.jpeg`} alt="Pilates reformer class" width={650} height={490}/></div></section>
  <section className="coach-intro"><h2>Meet Our Coach</h2><div className="coach-grid"><Image src={`${A}Coach.png`} alt="Winda Anggraini" width={440} height={610}/><div><p className="script">Pilates Expert</p><h3>WINDA ANGGRAINI</h3><p>Winda brings a thoughtful, encouraging approach to every class—so you can build strength, stability, and a better relationship with your body.</p><p>Her teaching makes mindful movement feel welcoming, precise, and deeply personal.</p><Link className="text-link" href="/our-coach">Meet Winda <span>→</span></Link></div></div></section>
  <section className="testimonials"><h2>What They Said</h2><div className="testimonial-grid">{testimonials.map(([img,name,text])=><article key={name}><Image src={`${A}${img}`} alt={name} width={150} height={150}/><h4>{name}</h4><p>{text}</p></article>)}</div></section>
</main><Footer /></>; }

const classes = [
  ["Reformer Pilates · Regular", "Every Tuesday & Thursday", "07.00 – 08.00 WIB", "3Motions Studio, Bogor", "Regular"],
  ["Mat Pilates · Regular", "Every Saturday", "08.00 – 09.15 WIB", "W-Clugra Racha Laras, Bogor", "Regular"],
  ["Pilates in Nature · Special", "29 August 2026", "07.00 – 09.30 WIB", "Sentul, Bogor", "Special"],
  ["Reformer Reset · Special", "12 September 2026", "09.00 – 11.00 WIB", "Sentul City, Bogor", "Special"],
];
export function SchedulePage() { return <><Header active="schedule"/><main><section className="hero inner-hero schedule-hero"><div className="hero-content"><p className="eyebrow">Move at your own rhythm</p><h1>Find Your<br/>Perfect Session</h1><p>Regular studio sessions and slow, restorative special classes held among the green landscapes of Bogor & Sentul.</p></div></section><section className="schedule"><p className="eyebrow red">3Motions calendar</p><h2>Upcoming Classes</h2><div className="schedule-note"><span>✦</span> Book your preferred session early—our intimate classes are intentionally kept small.</div><div className="table-wrap"><table><thead><tr><th>Class</th><th>Date</th><th>Time</th><th>Location</th><th></th></tr></thead><tbody>{classes.map((c)=><tr key={c[0]}><td><b>{c[0]}</b><small className={c[4].toLowerCase()}>{c[4]} course</small></td><td>{c[1]}</td><td>{c[2]}</td><td>{c[3]}</td><td><Button>Register Now</Button></td></tr>)}</tbody></table></div></section></main><Footer/></>; }

export function CoachPage() { return <><Header active="coach"/><main><section className="hero inner-hero coach-hero"><div className="hero-content"><p className="eyebrow">Meet the movement behind 3Motions</p><h1>Winda<br/>Anggraini</h1><p>Creating a place where women can move with confidence, curiosity, and care.</p></div></section><section className="coach-profile"><div className="profile-image"><Image src={`${A}Coach.png`} alt="Coach Winda Anggraini" width={570} height={760}/></div><div><p className="eyebrow red">Founder & Pilates Instructor</p><h2>Movement is a form of self-respect.</h2><p>For over five years, Winda Anggraini has helped women feel at home in their bodies through intentional, intelligent movement. Her classes pair classical Pilates foundations with a warm, modern approach that meets every member exactly where she is.</p><p>Winda believes that progress is not a rush toward perfection. It is the quiet confidence built by returning to yourself, one mindful repetition at a time.</p><div className="credentials"><div><b>5+</b><span>years teaching experience</span></div><div><b>300+</b><span>members supported</span></div><div><b>4</b><span>professional certifications</span></div></div></div></section><section className="cert-section"><p className="eyebrow red">Qualifications</p><h2>Trained to help you move well</h2><div className="cert-grid"><p><b>Comprehensive Pilates Instructor</b><br/>Certified in mat and reformer Pilates methodology.</p><p><b>Pre & Postnatal Pilates</b><br/>Specialist training for safe, empowering movement through motherhood.</p><p><b>Corrective Exercise</b><br/>Focused on posture, mobility, and building durable strength.</p></div></section><section className="coach-gallery"><Image src={`${A}AdobeStock_927779186.jpeg`} alt="Pilates documentation" width={700} height={480}/><Image src={`${A}AdobeStock_1905068241.jpeg`} alt="Pilates practice documentation" width={700} height={480}/></section></main><Footer/></>; }

export function AboutPage() { return <><Header active="about"/><main><section className="hero inner-hero about-hero"><div className="hero-content"><p className="eyebrow">A softer way to grow</p><h1>For Every<br/>Next Version of You</h1><p>3Motions is part of a bigger belief: when women move forward together, everyone rises.</p></div></section><section className="about-story"><div><p className="eyebrow red">Our story</p><h2>PT Teman Naik Kelas</h2><p>3Motions was created by PT Teman Naik Kelas, an Indonesian company built around a simple idea: growth feels more possible when it is shared.</p><p>We create warm, thoughtful spaces for women to care for their bodies, expand their confidence, and keep becoming. 3Motions is our invitation to make movement a joyful part of that journey.</p><Button>Start Your Journey</Button></div><Image src={`${A}AdobeStock_619494609.jpeg`} alt="Woman finding balance through movement" width={670} height={570}/></section><section className="about-values"><p className="eyebrow">Our north star</p><h2>Small moments. Lasting change.</h2><div className="values-grid"><article><span>01</span><h3>We make space</h3><p>A judgment-free studio that gives every woman room to arrive as she is.</p></article><article><span>02</span><h3>We grow together</h3><p>Progress feels better with a community that celebrates your next step.</p></article><article><span>03</span><h3>We move with purpose</h3><p>Every class is designed to leave you stronger, steadier, and more connected.</p></article></div></section><section className="about-cta"><Image src={`${A}AdobeStock_203252168.jpeg`} alt="Calm pilates space" width={1440} height={520}/><div><p className="eyebrow">Your place is here</p><h2>Let’s take the next step, together.</h2><Button>Explore Classes</Button></div></section></main><Footer/></>; }
